exclude: ['README.md']
permalink: pretty

collections:
  gdad:
    output: true
    permalink: /gdad/:path/
  apcsp:
    output: true
    permalink: /apcsp/:path/
  wdarchive:
    output: true
    permalink: /wdarchive/:path/
  gdarchive:
    output: true
    permalink: /gdarchive/:path/
  apcsa:
    output: true
    permalink: /apcsa/:path/
